# Generated by Django 5.2.7 on 2025-11-05 04:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproducto',
            name='variante',
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='productovariante',
            name='imagen_variante',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen específica que muestra esta variante (ej: el color)', max_length=255, null=True, verbose_name='producto_imagenes'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Imagen ropa', max_length=255),
        ),
    ]
