# Generated by Django 5.2.7 on 2025-11-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_imagenproducto_variante_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['producto', '-es_principal'], name='productos_i_product_d1dc58_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', '-creado_en'], name='productos_p_activo_63a45a_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='productos_p_categor_5dba6d_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='productos_p_slug_5e4b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['producto', 'activo'], name='productos_p_product_2411ed_idx'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['sku'], name='productos_p_sku_bb3265_idx'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['activo'], name='productos_p_activo_e7ee5e_idx'),
        ),
    ]
