# Generated by Django 5.2.7 on 2025-11-05 04:16

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_remove_pedido_direccion_envio_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('STRIPE', 'Stripe (Tarjeta)'), ('PAYPAL', 'PayPal'), ('QR_MANUAL', 'QR (BCP/Ganadero)')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('id_transaccion_pasarela', models.CharField(blank=True, db_index=True, help_text='ID de la transacción de Stripe, PayPal, etc.', max_length=255, null=True)),
                ('comprobante_qr', cloudinary.models.CloudinaryField(blank=True, help_text='Comprobante de pago para QR (subido por el usuario)', max_length=255, null=True, verbose_name='pagos/comprobantes_qr')),
                ('notas_admin', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ('-creado_en',),
            },
        ),
    ]
