# Generated by Django 5.2.7 on 2025-11-04 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Tienda Principal, Bodega Online', max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventario.almacen')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='productos.productovariante')),
            ],
            options={
                'verbose_name': 'Registro de Stock',
                'verbose_name_plural': 'Registros de Stock',
                'unique_together': {('variante', 'almacen')},
            },
        ),
    ]
