# Generated by Django 5.2.7 on 2025-11-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='capacidad',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad en m³ o unidades'),
        ),
    ]
